### ISSUE TITLE
Incompatible with latest Deno / TS

### ISSUE THREAD

**Issue by matteo-hertel** [Skillz4Killz/Discordeno#97]
**Describe the bug**
Discordeno is incompatible with latest Deno / TS

I saw a bunch of commits that are fixing this but there is no release for that so this issue is probably for the next person trying to figure out what they did wrong when the simple example won't work

Love the project btw 🙌 

**To Reproduce**
```
deno --version
deno 1.3.2
v8 8.6.334
typescript 4.0.2
```
using the simple bot in the documentation

```deno
import Client from "https://x.nest.land/Discordeno@7.3.0/src/module/client.ts";
import { sendMessage } from "https://x.nest.land/Discordeno@7.3.0/src/handlers/channel.ts";
import { Intents } from "https://x.nest.land/Discordeno@7.3.0/src/types/options.ts";
import config from "./config.ts";
Client({
    token: config.token,
    intents: [Intents.GUILD_MESSAGES, Intents.GUILDS],
    eventHandlers: {
        ready: () => {
            console.log(`Logged!`);
        },
        messageCreate: (message) => {
            if (message.content === "!ping") {
                sendMessage(message.channel, "Pong");
            }
        }
    }
});
```
1. run `deno run --allow-net --allow-read mod.ts`
2. See error

```
error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.owner_id;
         ~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:73:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.afk_channel_id;
         ~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:74:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.afk_timeout;
         ~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:75:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.verification_level;
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:78:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.mfa_level;
         ~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:79:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.system_channel_id;
         ~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:80:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.vanity_url_code;
         ~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:83:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.premium_tier;
         ~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:84:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.premium_subscription_count;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:85:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.preferred_locale;
         ~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:86:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.joined_at;
         ~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:87:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete guild.voice_states;
         ~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/guild.ts:89:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete message.channel_id;
         ~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/message.ts:26:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete message.mentions_everyone;
         ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/message.ts:28:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete message.mention_roles;
         ~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/message.ts:30:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
  delete message.edited_timestamp;
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/structures/message.ts:33:10

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete headers["Content-Type"];
           ~~~~~~~~~~~~~~~~~~~~~~~
    at https://iwa2o57bd3gy7nzbtujtzyuhtqu4ytlinyytm57d6npp2o47npha.arweave.net/RYGnd-EezY-3IZ0TPOKHnCnMTWhuMTZ34_Ne_Tufa84/src/module/requestManager.ts:157:12

Found 17 errors.

```

**Expected behavior**
No TS errors thrown in the console 

**Additional context**
Tested on 8.0.0 8.2.2 and 7.3.0

**Comment by Skillz4Killz** [comment]
Hey, please use version 8.4.1. I released them yesterday to nest.land, and announced it on the Discord server. I have been slowly trying to get users converted from using github to nest.land so i have not made any releases here on Github. But ill go ahead and do that now. For the forseeable future, join the discord server to get the latest news/updates 
![image](https://user-images.githubusercontent.com/23035000/91858042-afcc1c80-ec36-11ea-8feb-4483cc53ab0b.png)

**Comment by Skillz4Killz** [comment]
I've gone ahead and released it on Github for you as well.  https://github.com/Skillz4Killz/Discordeno/releases/tag/v8.4.1

Cheers 🎉 ❤️
